// RESPONSE TYPE KEYS FOR ACTIONS AND REDUCERS

// AUTH KEYS
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

// BOOKING KEYS
export const NEW_BOOKING_REQ = "NEW_BOOKING_REQ";
export const NEW_BOOKING_SUC = "NEW_BOOKING_SUC";
export const NEW_BOOKING_FAIL = "NEW_BOOKING_FAIL";

// SERVICES KEYS
export const SERVICES_REQ = "SERVICES_REQ";
export const SERVICES_SUC = "SERVICES_SUC";
export const SERVICES_FAIL = "SERVICES_FAIL";
