// RESPONSE TYPE KEYS FOR ACTIONS AND REDUCERS

// AUTH KEYS
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILURE = "PROFILE_FAILURE";

export const LOGOUT = "LOGOUT";

// BOOKING KEYS
export const BOOKING_REQ = "BOOKING_REQ";
export const BOOKING_SUC = "BOOKING_SUC";
export const BOOKING_FAIL = "BOOKING_FAIL";

// BOOKING YEARS KEYS
export const YEARS_REQ = "YEARS_REQ";
export const YEARS_SUC = "YEARS_SUC";
export const YEARS_FAIL = "YEARS_FAIL";

// SERVICES KEYS
export const SERVICES_REQ = "SERVICES_REQ";
export const SERVICES_SUC = "SERVICES_SUC";
export const SERVICES_FAIL = "SERVICES_FAIL";